environment:

  matrix:
    - PYTHON: "C:\\Python34"
   
install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install py2exe"

build: off

after_test:
  - "%PYTHON%\\python.exe setup.py py2exe"
  - "7z a elevator-win32-GUI-%APPVEYOR_BUILD_VERSION%.zip dist\\*"
  - "7z a elevator-win32-GUI-%APPVEYOR_BUILD_VERSION%.zip dist\\*"

artifacts:
  - path: elevator-win32-GUI-%APPVEYOR_BUILD_VERSION%.zip.zip
